variables:
  DOCKER_REPOSITORY: mendersoftware/iot-manager

stages:
  - test_prep
  - test
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-lint.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-unittests.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-acceptance.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-apidocs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:unit:
  variables:
    IOT_MANAGER_MONGO: mongo

test:govendor-check:
  variables:
    GOLANG_VERSION: '1.18'

test:acceptance_tests:
  stage: test
  needs: []
  rules:
    - if: '$CI_COMMIT_TAG =~ /^saas-[a-zA-Z0-9.]+$/'
      when: never
    - when: on_success
  tags:
    - docker
  image: docker:23.0.4-alpine3.17
  services:
    - name: docker:23.0.6-dind-alpine3.17
      alias: docker
  before_script:
    - apk add docker-compose make
  script:
    - rm -f tests/coverage*.txt
    - make acceptance-tests
  artifacts:
    expire_in: 2w
    paths:
      - tests/acceptance.*
      - tests/coverage-acceptance.txt
    when: always
