# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: IOT_MANAGER_LISTEN

listen: :8080

# Mongodb connection string
# Defaults to: "mongodb://localhost"
# Overwrite with environment variable: IOT_MANAGER_MONGO_URL

mongo_url: mongodb://mender-mongo:27017

# Mongodb database name
# Defaults to: "iot_manager"
# Overwrite with environment variable: IOT_MANAGER_MONGO_DBNAME

mongo_dbname: iot_manager

# Enable SSL for mongo connections
# Defaults to: false
# Overwrite with environment variable: IOT_MANAGER_MONGO_SSL

# mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# Overwrite with environment variable: IOT_MANAGER_MONGO_SSL_SKIPVERIFY

# mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# Overwrite with environment variable: IOT_MANAGER_MONGO_USERNAME

# mongo_username: user

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# Overwrite with environment variable: IOT_MANAGER_MONGO_PASSWORD

# mongo_password: secret


# AES encryption key
# 32 bytes long key used to encrypt and decrypt sensitive data stored
# in the database; encryption is disabled if the key is empty. The value
# must be a a valid base64 encoded 32 bytes secret.
# Defaults to: ""
# Overwrite with environment variable: IOT_MANAGER_AES_ENCRYPTION_KEY

# aes_encryption_key:


# AES encryption fallback key
# fallback key used when performing key-rotation; if set, it will be used
# as fallback key to decrypt the data stored in the database if the primary
# key fails. The value must be a a valid base64 encoded 32 bytes secret.
# Defaults to: ""
# Overwrite with environment variable: IOT_MANAGER_AES_ENCRYPTION_FALLBACK_KEY

# aes_encryption_fallback_key:


# Workflows URL
# Overwrites the URL to the workflows service.
# Defaults to: http://mender-workflows-server:8080
# Overwrite with environment variable: IOT_MANAGER_WORKFLOWS_URL
#
# workflows_url: http://mender-workflows-server:8080

# Deviceauth URL
# Overwrites the URL to the deviceauth service.
# Defaults to: http://mender-device-auth:8080
# Overwrite with environment variable: IOT_MANAGER_DEVICEAUTH_URL
#
# deviceauth_url: http://mender-device-auth:8080

# Webooks request timeout in seconds
# Defaults to: 10
# Overwrite with environment variable: IOT_MANAGER_WEBHOOKS_TIMEOUT_SECONDS
#
# webhooks_timeout_seconds: 10
