// Copyright 2022 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	aws "github.com/aws/aws-sdk-go-v2/aws"

	iotcore "github.com/mendersoftware/iot-manager/client/iotcore"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// DeleteDevice provides a mock function with given fields: ctx, cfg, deviceID
func (_m *Client) DeleteDevice(ctx context.Context, cfg *aws.Config, deviceID string) error {
	ret := _m.Called(ctx, cfg, deviceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *aws.Config, string) error); ok {
		r0 = rf(ctx, cfg, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDevice provides a mock function with given fields: ctx, cfg, deviceID
func (_m *Client) GetDevice(ctx context.Context, cfg *aws.Config, deviceID string) (*iotcore.Device, error) {
	ret := _m.Called(ctx, cfg, deviceID)

	var r0 *iotcore.Device
	if rf, ok := ret.Get(0).(func(context.Context, *aws.Config, string) *iotcore.Device); ok {
		r0 = rf(ctx, cfg, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iotcore.Device)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *aws.Config, string) error); ok {
		r1 = rf(ctx, cfg, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertDevice provides a mock function with given fields: ctx, cfg, deviceID, device, policy
func (_m *Client) UpsertDevice(ctx context.Context, cfg *aws.Config, deviceID string, device *iotcore.Device, policy string) (*iotcore.Device, error) {
	ret := _m.Called(ctx, cfg, deviceID, device, policy)

	var r0 *iotcore.Device
	if rf, ok := ret.Get(0).(func(context.Context, *aws.Config, string, *iotcore.Device, string) *iotcore.Device); ok {
		r0 = rf(ctx, cfg, deviceID, device, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iotcore.Device)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *aws.Config, string, *iotcore.Device, string) error); ok {
		r1 = rf(ctx, cfg, deviceID, device, policy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
